server:
  port : 8823
  servlet:
    context-path: /${spring.application.name}/v1

spring:
  data:
    mongodb:
      database: datahub
      uri: mongodb://localhost:27017/datahub
  kafka:
    consumer:
      bootstrap-servers: ec2-52-23-230-199.compute-1.amazonaws.com:9092
      group-id: consumer-group-${spring.application.name}
      auto-offset-reset: earliest
#      heartbeat-interval:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      client-id: ${spring.application.name}-producer
      bootstrap-servers: ec2-52-23-230-199.compute-1.amazonaws.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 100MB
      batch-size: 10MB
com:
  vape:
    dsp:
      integration:
        uri: https://api.lambda.dsp-engine.vibraneur.com/v1/algorithms
        kurtosis: ${com.vape.dsp.integration.uri}/kurtosis
        fft: ${com.vape.dsp.integration.uri}/fft
        crest: ${com.vape.dsp.integration.uri}/crest
        shape: ${com.vape.dsp.integration.uri}/shape
        rms: ${com.vape.dsp.integration.uri}/rms
        api-key: quGExBzlcX12uPC3EiaZBau8SVtQKWf9Gy6yEBZ6
